# Generated by Django 4.2.17 on 2024-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('years_of_life', models.CharField(blank=True, max_length=50, null=True)),
                ('biography', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='person_photos/')),
                ('image2', models.ImageField(blank=True, upload_to='person_photos/')),
                ('image3', models.ImageField(blank=True, upload_to='person_photos/')),
                ('image4', models.ImageField(blank=True, upload_to='person_photos/')),
                ('image5', models.ImageField(blank=True, upload_to='person_photos/')),
            ],
        ),
    ]
